### ISSUE TITLE
everyone's names in footer

### ISSUE THREAD

**Issue by nellarro** [nellarro/build-it-together#10]
There should be a footer with everyone's name who contributed to the project. 

- [x] Footer should have a background color of #0B5563
- [x] Names should be links that link to each student GitHub profile
- [x] Names should be 12pt bold, italic, #fff 
- [x] Names should be #FFCB77 when hovered
- [x] Names should be #E83151 after they have been visited

**Comment by JLevelston** [comment]
*JaNiece Levelston
