### ISSUE TITLE
need header with logo

### ISSUE THREAD

**Issue by nellarro** [nellarro/build-it-together#4]
- [ ] Logo should be in the top left
- [ ] Logo should be height: 4em width: 8em

 In mobile:
- [ ] Logo should do a 180 spin when hovered

In tablet:
- [ ] Logo should flip on the y axis

In desktop:
- [ ] Logo should get slightly larger and then go back to its normal size

**Logo:**
![bot](https://user-images.githubusercontent.com/18720522/90991441-1b4b2580-e577-11ea-85dc-39990b5d241c.jpg)

**Comment by codingpixi** [comment]
Detra
