### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by nellarro** [nellarro/build-it-together#9]
- [x] When background color is #5E5C6C, text should be bold, white, and 16px
- [x] When background color is #FFCB77, text should be normal, black and 14px

**Comment by codingpixi** [comment]
Detra

**Comment by nellarro** [comment]
Assigned to Richard

**Comment by dontbecypher16** [comment]
Do I need to switch colors in the background or just choose one of those? This is just for the body right?

**Comment by nellarro** [comment]
@dontbecypher16, this is only for the text. There's another issue that relates specifically to the background color. It'd be a great idea to collaborate with @thetechtakeover because he is working on #8 which requires media queries for the background color changes. 

Since this requires media queries as well, you all might want to work together to make sure you're re-using your media queries and not writing duplicate code.

**Comment by thetechtakeover** [comment]
@dontbecypher16 did you get a chance to complete the media queries to be merge? I think I need to insert the background colors at different the different media sizes

**Comment by dontbecypher16** [comment]
@thetechtakeover Im just getting off work like 40 mins ago. Im trying right now to go through everything and see what needs to be done. I didnt merge it yet because I wanted to see what you had done.

**Comment by thetechtakeover** [comment]
@dontbecypher16 cool. I put my number in the classroom if you want to text me if you need help. I'm for a while tonight or we call meet online tomorrow

**Comment by dontbecypher16** [comment]
We can wait until later this morning. Nellarro just announced a meeting at 11:30am.  We can get things sorted out then. This will give me time to work on some C# code on another project I'm doing.
